import numpy as np
arr1=np.arange(4,dtype=float).reshape(2,2)
print(arr1)
arr2=np.array([2,2])
print(arr2)
print()
print(np.add(arr1,arr2))
print(np.subtract(arr1,arr2))
print(np.multiply(arr1,arr2))
print(np.divide(arr1,arr2))